### PR TITLE
[Containers] fix sum of DenseAxisArray that doesn't support zero(T)

### LINKED ISSUE #4096: MethodError: no method matching zero(::Type{Any})
Hello!

Despite using latest JuMP 1.29.3, when executing the following code, I obtain the error:
```
MethodError: no method matching zero(::Type{Any})
This error has been manually thrown, explicitly, so the method may exist but be intentionally marked as unimplemented.

Closest candidates are:
  zero(::Type{Union{Missing, T}}) where T
   @ Base missing.jl:105
  zero(!Matched::Type{Union{}}, Any...)
   @ Base number.jl:310
  zero(!Matched::Type{LibGit2.GitHash})
   @ LibGit2 C:\Users\Davide\.julia\juliaup\julia-1.11.5+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LibGit2\src\oid.jl:221
  ...
```
This occurs in function
```
function Base.sum(
    f::F,
    x::Union{DenseAxisArray{T},DenseAxisArrayView{T}};
    dims = Colon(),
    init = zero(T),
)
```
where x is a denseaxisarray as in the following figure:

Image

Image

I believe this occurs because T is any, thus zero(T) triggers the error.

The following code reproduces the error:
``` julia
using EnergyCommunity, HiGHS

folder = joinpath(@__DIR__, "data")
create_example_data(folder, config_name="default")

input_file = joinpath(@__DIR__, "data/energy_community_model.yml")  # Input file

ECModel = ModelEC(input_file, EnergyCommunity.GroupCO(), HiGHS.Optimizer)
reset_user_set!(ECModel)

utility_callback = to_utility_callback_by_subgroup(ECModel,GroupNC())
utility_callback([EC_CODE; ECModel.user_set])
```

I'm using latest JuMP and EnergyCommunity.jl versions:
```
[[deps.JuMP]]
deps = ["LinearAlgebra", "MacroTools", "MathOptInterface", "MutableArithmetics", "OrderedCollections", "PrecompileTools", "Printf", "SparseArrays"]
git-tree-sha1 = "b76f23c45d75e27e3e9cbd2ee68d8e39491052d0"
uuid = "4076af6c-e467-56ae-b986-b466b2749572"
version = "1.29.3"

    [deps.JuMP.extensions]
    JuMPDimensionalDataExt = "DimensionalData"

    [deps.JuMP.weakdeps]
    DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"

[[deps.EnergyCommunity]]
deps = ["CSV", "DataFrames", "ExportAll", "FileIO", "Format", "Formatting", "InteractiveUtils", "JuMP", "LayeredLayouts", "MathOptInterface", "Plots", "SankeyPlots", "StatsPlots", "TheoryOfGames", "XLSX", "YAML"]
git-tree-sha1 = "7d14c433c7cf6f2ee258f27164174e587454fd80"
uuid = "2f2d8a28-e724-42c4-aa4e-51fe4e6b7a61"
version = "0.2.2"
```

### PR DESCRIPTION
**Pull request by odow**
We can't dispatch on keyword types, so we need to implement a run-time dispatch.

Closes #4096

### CODE REVIEW

File: test/Containers/test_macro.jl [hunk 1]
```diff
@@ -279,4 +279,11 @@ function test_trailing_semicolon()
     return
 end
 
+function test_init_issue_4096()
+    x = Containers.DenseAxisArray(Any[1, 2, 3], Int[1, 2, 3])
+    @test sum(x) == 6
```
Comment (blegat) [inline test/Containers/test_macro.jl]: Can you add a test with `@allocated ... == 0` to check that the dispatch is done a compile time ? It think it is still able to do this if-else at compile time
