### PR TITLE
Better error messages when working with matrices in constraints

### LINKED ISSUE #1465: Constraints with MOI PSD Cones
The following constraint,
```
@constraint(model, X in MOI.PositiveSemidefiniteConeSquare(size(X,1)))
```
Results in the following error message,
```
ERROR: MethodError: no method matching build_constraint(::JuMP.#_error#74{Symbol}, ::Array{JuMP.GenericAffExpr{Float64,JuMP.VariableRef},2}, ::MathOptInterface.PositiveSemidefiniteConeSquare)
```

### PR DESCRIPTION
**Pull request by odow**
Closes #1465

### CODE REVIEW

File: src/macros.jl [hunk 1]
```diff
@@ -417,6 +417,18 @@ function build_constraint(_error::Function, x::AbstractArray,
...
+function build_constraint(
+        _error::Function, x::Matrix, set::MOI.AbstractVectorSet)
+    return _error(
+        "unexpected matrix in vector constraint. Do you need to flatten the " *
+        "matrix into a vector using `vec()`?")
+end
+
+function build_constraint(_error::Function, ::Matrix, T::Union{
+    MOI.PositiveSemidefiniteConeSquare, MOI.PositiveSemidefiniteConeTriangle})
+    return _error("instead of `$(T)`, use `JuMP.PSD()`.")
```
Comment (mlubin) [inline src/macros.jl]: JuMP.PSDCone?
