### PR TITLE
Fix #887

### LINKED ISSUE #887: MethodError when matrix-multiplying transpose of sparse matrix
I get the following error when attempting to matrix-multiply a constant (in this case integer) vector by the transpose of a sparse matrix of variables i.e.
```julia
x'*v
```
where `v` is a constant, `Int64`-valued vector.

```
ERROR: MethodError: no method matching Ac_mul_B!(::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::SparseMatrixCSC{JuMP.Variable,Int64}, ::Array{Int64,1}, ::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::Array{JuMP.GenericAffExpr{Float64,JuMP.Variable},1})
Closest candidates are:
  Ac_mul_B!(::Number, ::SparseMatrixCSC{Tv,Ti<:Integer}, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Number, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}) at sparse/linalg.jl:51
  Ac_mul_B!(::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::SparseMatrixCSC{Tv,Ti<:Integer}, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}) at sparse/linalg.jl:97
  Ac_mul_B!(::AbstractArray{T,1}, ::Union{AbstractArray{T,1},AbstractArray{T,2}}, ::AbstractArray{T,1}) at linalg/matmul.jl:123
  ...
 in Ac_mul_B(::SparseMatrixCSC{JuMP.Variable,Int64}, ::Array{Int64,1}) at ./sparse/linalg.jl:85
```

This seems very strange to me because `x*w` works perfectly fine.

A workaround is available by doing 
```julia
(v'*x)'
```

### PR DESCRIPTION
**Pull request by ExpandingMan**
It appears that the definitions for `*` in lines 406, 407 and 408 were missing the type `Vector` in the unions of their first arguments, even though it seems that the methods for this are fully implemented.

Edit: This is a very wrong statement.  See below.

### CODE REVIEW

**Comment by mlubin** [comment]
Could you add unit test for the failure in #887?

**Comment by ExpandingMan** [comment]
Sure.  Bear with me a bit, I'm actually pretty new to contributing to existing projects that are not my own, still figuring out the process...

**Comment by ExpandingMan** [comment]
Where's the appropriate place to create the unit test?  In the test directory of my fork?  Do you guys have any kind of standardized way of writing them?

**Comment by mlubin** [comment]
I would add the relevant tests under this block: https://github.com/JuliaOpt/JuMP.jl/blob/b1a7bda717a0d8fae5a9f8169cf3495f8bfb6fa5/test/operator.jl#L521
If you push to the ``patch-1`` branch on your fork the changes will show up under this PR.

**Comment by ExpandingMan** [comment]
Ok, I added a few more lines to the unit test.  There are several errors, but all of them existed before my new change, they just weren't caught in the unit tests.  Multiplying sparse matrices of floats by sparse matrices of `Variable` still isn't implemented.

The really weird error is that `X'*A` isn't working (throws "No method matching `Ac_mul_B!`), where `X` is a sparse matrix of variables but `A` is a sparse matrix of floats.  This weird because `A'*X` and `X*A` work fine.  I'm wondering if there would be anything wrong with defining the operators such that `X'*A` is defined as `(A'*X)'`.

Anyway, I haven't found any errors with defining multiplication of sparse matrices of variables by vectors, so I think this pull is ok...

File: test/operator.jl [hunk 1]
```diff
@@ -586,6 +590,25 @@ const sub2 = JuMP.repl[:sub2]
...
+                            X11   X23  0
+                            0     2X23 0])
+        @test vec_eq(X'*A, [2X11  X11  0
+                            0     0    0
+                            X23   2X23 X23])
+        @test vec_eq(X*A, X*B)
+        @test vec_eq(A*X, B*X)
+        @test vec_eq(A*X', B*X')
+        # TODO this is known to fail currently
+        @test vec_eq(X'*A, X'*B)
```
Comment (mlubin) [inline test/operator.jl]: Use ``@test_broken`` if it's known to fail

Comment (ExpandingMan) [inline test/operator.jl]: Done.  There is an error in the concatenation section, but I don't think it's new.

**Comment by mlubin** [comment]
Tests are failing: https://travis-ci.org/JuliaOpt/JuMP.jl/jobs/181483226#L319

**Comment by ExpandingMan** [comment]
This was not the issue. 

I had forgotten that, confusingly, Julia makes transposed vectors `Matrix`, which is why `Vector` was not defined in those expressions.  Still looking into it now...

**Comment by ExpandingMan** [comment]
Wow... after a great deal of confusion, I have tracked down the issue, and it is *really* strange.  See the following code
```julia
import Base.*

function (*)(A::SparseMatrixCSC{Int32}, B::Vector) 
    println("being called!")
end

A = spzeros(Int64, 3, 3)
A[1,1] = 2
A[3,3] = 4

B = spzeros(Int32, 3, 3)
B[1,1] = 2
B[3,3] = 4

v = rand(0:99, 3)

A*v == A'*v  # evaluates to true
B*v == B'*v  # evaluates to false, rhs never gets overloaded!
typeof(B) == typeof(B') # even though this evaluates to true!

transpose(B)*v # however this uses the new method defined above
```
Somehow, even though the multiplication of a vector by a transposed sparse matrix involves *exactly* the same types as the multiplication of a vector by a non-transposed sparse matrix, a completely different method gets called!  

The reason this happens is because if you do `A'*v` it **does not call `*`**, no, no, no... instead it calls `Ac_mul_B`, a completely different function.  Apparently unlike ordinary functions, operator symbols like `*` can act as aliases for multiple different functions depending on the context.

Part of the problem is that I've been using the adjoint instead of `transpose`, but since that is a perfectly legitimate thing to do, it should still be fixed (besides, nobody wants to write `transpose(A)`).

I should be able to fix this now by creating a new `Ac_mul_B` method.  Give me a bit to test it...

**Comment by blegat** [comment]
That is indeed surprising, I guess this is to avoid applying the transpose operator.
Note that `A'` is the conjugate transpose (`ctranspose`, `Ac_mul_B`) while `A.'` is the transpose (`transpose`, `At_mul_B`) so it might also make sense to define `At_mul_B` which should be equivalent to `Ac_mul_B` as long as no complex numbers are involved.

**Comment by ExpandingMan** [comment]
Yes, but the very strange thing is that `transpose(A)*v` seems to call `*` (still investigating).  I didn't realize until now that `A.'` gave the transpose.  I think since JuMP doesn't have complex numbers implemented it makes sense to define `Ac_mul_B`.  Besides, it is frequently the case that the transpose operator on real matrices generalizes to the adjoint operator on complex matrices.

I might raise an issue about this in Julia main, at the very least it should be more well documented.

**Comment by ExpandingMan** [comment]
Ok... I have now definitely fixed the real problem.  I had to make the following additions to operators.jl
* There are now `At_mul_B` and `Ac_mul_B` methods for each of the `*` matrix multiplication methods.
* Those call a new method `_matmult` which is equivalent to `_matmul` but for the first matrix transposed.
* That in turn calls the new methods `_return_arrayt` and `_multiplyt!`.
* `_return_arrayt` gets the proper return array for multiplication with the first matrix transposed.
* The `_multiplyt!` methods are the equivalent to `_multiply!` methods except that the first matrix is transposed.  They should be as efficient as `_multiply!` (i.e. `transpose` is only called for a `SparseMatrixCSC`).
* The sparse-matrix, sparse-matrix `_multiplyt!` implementation is every bit as bad as the one the existing `_multiply!` one, at some point we need to add efficient sparse-matrix multiplication.

There are now two broken unit tests: but I have confirmed that they were broken prior to my changes.  Multiplying a transposed sparse matrix of variables by another matrix still doesn't work.  I believe this can be fixed by adding `A_mul_Bc` and `A_mul_Bt` methods, but I didn't want to do that yet as there is still a lot of work to be done on sparse matrices in general.

There is still #907, which I don't completely understand.  All matrix multiplications call `append!` so that particular warning should not pop up.  We should also try to understand why it is so damn slow.

File: src/operators.jl [hunk 2]
```diff
@@ -398,15 +418,45 @@ function _multiply!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs
...
 
 _multiply!(ret, lhs, rhs) = A_mul_B!(ret, lhs, ret)
 
 (*){T<:JuMPTypes}(             A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix,   Vector,   SparseMatrixCSC})    = _matmul(A, x)
 (*){T<:JuMPTypes,R<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix{R},Vector{R},SparseMatrixCSC{R}}) = _matmul(A, x)
 (*){T<:JuMPTypes}(             A::Union{Matrix,   SparseMatrixCSC},    x::Union{Matrix{T},Vector{T},SparseMatrixCSC{T}}) = _matmul(A, x)
 
+import Base.At_mul_B
+import Base.Ac_mul_B
+# confusingly, these methods are called when one does A'*v or A.'*v respectively
```
Comment (mlubin) [inline src/operators.jl]: Let's drop "confusingly" here and keep the comment strictly factual.

File: src/operators.jl [hunk 3]
```diff
@@ -398,15 +418,45 @@ function _multiply!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs
...
+At_mul_B{T<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix, Vector, SparseMatrixCSC}) = _matmult(A, x)
+At_mul_B{T<:JuMPTypes,R<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix{R}, Vector{R}, SparseMatrixCSC{R}}) = _matmult(A, x)
+At_mul_B{T<:JuMPTypes}(A::Union{Matrix,SparseMatrixCSC}, x::Union{Matrix{T}, Vector{T}, SparseMatrixCSC{T}}) = _matmult(A, X)
+# these methods are the same as a bove since complex numbers are not implemented in JuMP
```
Comment (mlubin) [inline src/operators.jl]: "a bove" should be "above"

File: test/operator.jl [hunk 4]
```diff
@@ -586,6 +590,31 @@ const sub2 = JuMP.repl[:sub2]
...
+                            0     2X23 0])
+        @test vec_eq(X'*A, [2X11  X11  0
+                            0     0    0
+                            X23   2X23 X23])
+        @test vec_eq(X.'*A, [2X11 X11  0 
+                             0    0    0
+                             X23  2X23 X23])
+        @test vec_eq(X.'*A, X'*A)
+        @test vec_eq(X*A, X*B)
+        @test_broken vec_eq(A*X, B*X)
```
Comment (mlubin) [inline test/operator.jl]: Can you comment these out for now? They're causing travis to report failures.

**Comment by mlubin** [comment]
@joehuchette, could you review?

**Comment by mlubin** [comment]
@ExpandingMan, your commits are not properly linked to your github account.

**Comment by ExpandingMan** [comment]
Hmm... I have no idea why that would be.  Any idea how I fix that?

**Comment by mlubin** [comment]
https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by ExpandingMan** [comment]
Made a trivial commit (deleted space in comment) to fix user email.

**Comment by mlubin** [comment]
You can rebase the commits to clean them all up

**Comment by ExpandingMan** [comment]
I can rebase the commits locally, but for some reason I am unable to push them...

**Comment by blegat** [comment]
You need to do `git push -f ...` when you rebase. This is because in addition to adding new commits you also modify commits already pushed to you need to force the push hence the `-f`.

**Comment by ExpandingMan** [comment]
I did that... how do I change only the user name when calling `git rebase`?  I am brought to the script but I can only do things like squash or reword, I think my change wasn't doing anything.  Is there a command for changing the user?  

I apologize for my complete inexperience with this.

**Comment by blegat** [comment]
You will find the answer [here](http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit). No problem ;)

**Comment by ExpandingMan** [comment]
Ok, got it, thanks for your help.

File: src/operators.jl [hunk 5]
```diff
@@ -398,15 +418,45 @@ function _multiply!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs
...
 (*){T<:JuMPTypes}(             A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix,   Vector,   SparseMatrixCSC})    = _matmul(A, x)
 (*){T<:JuMPTypes,R<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix{R},Vector{R},SparseMatrixCSC{R}}) = _matmul(A, x)
 (*){T<:JuMPTypes}(             A::Union{Matrix,   SparseMatrixCSC},    x::Union{Matrix{T},Vector{T},SparseMatrixCSC{T}}) = _matmul(A, x)
 
+import Base.At_mul_B
+import Base.Ac_mul_B
+# these methods are called when one does A.'*v or A'*v respectively 
+At_mul_B{T<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix, Vector, SparseMatrixCSC}) = _matmult(A, x)
+At_mul_B{T<:JuMPTypes,R<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix{R}, Vector{R}, SparseMatrixCSC{R}}) = _matmult(A, x)
+At_mul_B{T<:JuMPTypes}(A::Union{Matrix,SparseMatrixCSC}, x::Union{Matrix{T}, Vector{T}, SparseMatrixCSC{T}}) = _matmult(A, X)
```
Comment (joehuchette) [inline src/operators.jl]: ``_matmult(A, x)``

File: src/operators.jl [hunk 6]
```diff
@@ -398,15 +418,45 @@ function _multiply!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs
...
+# these methods are the same as above since complex numbers are not implemented in JuMP
+Ac_mul_B{T<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix, Vector, SparseMatrixCSC}) = _matmult(A, x)
+Ac_mul_B{T<:JuMPTypes,R<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix{R}, Vector{R}, SparseMatrixCSC{R}}) = _matmult(A, x)
+Ac_mul_B{T<:JuMPTypes}(A::Union{Matrix,SparseMatrixCSC}, x::Union{Matrix{T}, Vector{T}, SparseMatrixCSC{T}}) = _matmult(A, X)
```
Comment (joehuchette) [inline src/operators.jl]: ``_matmult(A, x)``

File: src/operators.jl (hunk 5 above)
Comment (ExpandingMan) [inline src/operators.jl]: not sure what you're asking here...

**Comment by ExpandingMan** [comment]
Currently working on adding tests that should cover the rest of the functions.

File: src/operators.jl (hunk 5 above)
Comment (joehuchette) [inline src/operators.jl]: The argument to the function is ``x`` (lowercase), while the argument you pass to ``_matmult`` is ``X`` (uppercase).

**Comment by mlubin** [comment]
The new code should be 100% covered by unit tests to catch issues like this.

On Dec 7, 2016 10:30, "ExpandingMan" <notifications@github.com> wrote:

*@ExpandingMan* commented on this pull request.
------------------------------

In src/operators.jl <https://github.com/JuliaOpt/JuMP.jl/pull/908>:

>
 _multiply!(ret, lhs, rhs) = A_mul_B!(ret, lhs, ret)

 (*){T<:JuMPTypes}(
A::Union{Matrix{T},SparseMatrixCSC{T}}, x::Union{Matrix,   Vector,
SparseMatrixCSC})    = _matmul(A, x)
 (*){T<:JuMPTypes,R<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}},
x::Union{Matrix{R},Vector{R},SparseMatrixCSC{R}}) = _matmul(A, x)
 (*){T<:JuMPTypes}(             A::Union{Matrix,   SparseMatrixCSC},
 x::Union{Matrix{T},Vector{T},SparseMatrixCSC{T}}) = _matmul(A, x)

+import Base.At_mul_B
+import Base.Ac_mul_B
+# these methods are called when one does A.'*v or A'*v respectively
+At_mul_B{T<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}},
x::Union{Matrix, Vector, SparseMatrixCSC}) = _matmult(A, x)
+At_mul_B{T<:JuMPTypes,R<:JuMPTypes}(A::Union{Matrix{T},SparseMatrixCSC{T}},
x::Union{Matrix{R}, Vector{R}, SparseMatrixCSC{R}}) = _matmult(A, x)
+At_mul_B{T<:JuMPTypes}(A::Union{Matrix,SparseMatrixCSC},
x::Union{Matrix{T}, Vector{T}, SparseMatrixCSC{T}}) = _matmult(A, X)

Ah, good catch, thanks!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/JuliaOpt/JuMP.jl/pull/908>, or mute the thread

**Comment by ExpandingMan** [comment]
How do I trigger the codecov to run again?

**Comment by joehuchette** [comment]
Let's see if that works. Otherwise, you can run the [code coverage locally](https://github.com/JuliaCI/Coverage.jl).

**Comment by ExpandingMan** [comment]
Ok, looking good, all of my code seems to be covered and tests are passing.  I'm still a bit confused about how I publish the coverage report though... It seems very strange to me that one of us can't just trigger it to run again.

File: src/operators.jl [hunk 7]
```diff
@@ -369,6 +369,21 @@ function _multiply!{T<:JuMPTypes}(ret::Array{T}, lhs::Array, rhs::Array)
     ret
 end
 
+# this for transposed multiplication
```
Comment (mlubin) [inline src/operators.jl]: Please expand on the comment. Does this compute ``lhs'*rhs``?

File: src/operators.jl [hunk 8]
```diff
@@ -382,6 +397,11 @@ function _multiply!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs
     ret
 end
 
+# this computes lhs.'*rhs and places it in ret
+function _multiplyt!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs::SparseMatrixCSC, rhs::Array)
+    _multiply!(ret, transpose(lhs), rhs) # for sparse matrices this should be cheap
```
Comment (mlubin) [inline src/operators.jl]: I'm not sure if i'd call transposing a sparse matrix cheap, it actually could be relatively slow. Maybe leave a smarter implementation as a TODO?

Comment (ExpandingMan) [inline src/operators.jl]: Funny you should mention that, I was literally just this second about to make a post about it.  Part of the reason I didn't actually test how expensive this was is because sparse matrix multiplication is currently broken (i.e. way slower than it should be), so this will all have to change anyway.  See issue #907 .

**Comment by ExpandingMan** [comment]
Hello all.  I'm pretty sure my code for `_multiplyt!` on line 422 which is based on `_multiply!` on line 405 is correct, but it uses some really bizarre variable names (`multivec_row`?) which right now is making me paranoid.  If somebody can look at it and check me carefully, I would be appreciated, although it does seem to be producing the correct result.

File: test/operator.jl [hunk 9]
```diff
@@ -586,6 +599,42 @@ const sub2 = JuMP.repl[:sub2]
...
+        @test vec_eq(Y'*A, Y.'*A)
+        @test vec_eq(A*Y', A*Y.')
+        @test vec_eq(Z'*A, Z.'*A)
+        @test vec_eq(Xd'*Y, Xd.'*Y)
+        @test vec_eq(Y'*Xd, Y.'*Xd)
+        @test vec_eq(Xd'*Xd, Xd.'*Xd)
+        # @test_broken vec_eq(A*X, B*X)
+        # @test_broken vec_eq(A*X', B*X')
+        @test vec_eq(X'*A, X'*B)
+        # @test_broken(X'*X, X.'*X) # sparse quadratic known to be broken
```
Comment (mlubin) [inline test/operator.jl]: Why is this known to be broken? If it's known could you write down a reference?

Comment (ExpandingMan) [inline test/operator.jl]: It is part of a plethora of existing problems with sparse-matrix multiplication, which really needs to be reimplemented (see #907, which still has me confused).  I haven't made an issue for this particular problem.  Give me a few minutes to go back to master and check the error it throws, and I'll create a new issue for it.

Sorry my comments aren't better, I'm a physicist rather than a software engineer by training, so even this is one of the most formal code-writing processes I've ever been through!  I'll try to keep things a little clearer.

Comment (mlubin) [inline test/operator.jl]: Don't worry, you're doing a good job. None of us are software engineers :)

File: src/operators.jl [hunk 10]
```diff
@@ -398,15 +418,45 @@ function _multiply!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs
     ret
 end
 
+# this computes lhs.'*rhs and places it in ret
+function _multiplyt!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs::Matrix, rhs::SparseMatrixCSC)
+    rowval = rhs.rowval
+    nzval  = rhs.nzval
+    for multivec_row ∈ 1:size(lhs,2) # transpose
+        for col ∈ 1:rhs.n
+            idxset = rhs.colptr[col]:(rhs.colptr[col+1]-1)
```
Comment (mlubin) [inline src/operators.jl]: It's better to use ``nzrange`` here

File: src/operators.jl [hunk 11]
```diff
@@ -398,15 +418,45 @@ function _multiply!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs
     ret
 end
 
+# this computes lhs.'*rhs and places it in ret
+function _multiplyt!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs::Matrix, rhs::SparseMatrixCSC)
+    rowval = rhs.rowval
+    nzval  = rhs.nzval
```
Comment (mlubin) [inline src/operators.jl]: and ``nonzeros(rhs)``

File: src/operators.jl (hunk 10 above)
Comment (mlubin) [inline src/operators.jl]: If you could update ``_multiply!`` above for consistency then I think we're all set

File: src/operators.jl [hunk 12]
```diff
@@ -358,55 +358,105 @@ Base.diagm(x::Vector{Variable}) = diagm(convert(Vector{AffExpr}, x))
...
     ret
 end
 
+# this computes lhs.'*rhs and places it in ret
+function _multiplyt!{T<:Union{GenericAffExpr,GenericQuadExpr}}(ret::Array{T}, lhs::Matrix, rhs::SparseMatrixCSC)
+    rowval = rowvals(rhs)
+    nzval  = nonzeros(rhs)
+    for multivec_row ∈ 1:size(lhs,2) # transpose
+        for col ∈ 1:rhs.n
+            idxset = rhs.colptr[col]:(rhs.colptr[col+1]-1)
```
Comment (mlubin) [inline src/operators.jl]: ``nzrange(rhs,col)`` should replace ``rhs.colptr[col]:(rhs.colptr[col+1]-1)``

**Comment by mlubin** [comment]
@ExpandingMan @joehuchette, does this PR also fix https://github.com/JuliaOpt/JuMP.jl/issues/600?

**Comment by joehuchette** [comment]
It should. 






On Thu, Dec 8, 2016 at 10:20 PM -0500, "Miles Lubin" <notifications@github.com> wrote:












@ExpandingMan @joehuchette, does this PR also fix #600?

**Comment by ExpandingMan** [comment]
Yes, it fixes #600, but bear in mind, there are a lot of methods that ultimately need to get overloaded.
```julia
*         # "A_mul_B", done
At_mul_B  # done in this patch
A_mul_Bt
At_mul_Bt

Ac_mul_B  # done in this patch
A_mul_Bc
Ac_mul_Bc
```
But really, since there is no implementation of complex numbers in JuMP, it's only two more because the adjoint is equivalent to the transpose for all real matrices.

Again, I didn't bother to fix the others yet because there is still something quite wrong with the sparse matrix multiplication ( #907), so I didn't want to go too crazy until that is completely figured out.

It would be really, really nice if someone would write a package with macros for creating all this "boiler-plate" linear algebra code for custom types.  It's a little complicated, but I definitely think it's doable.  I might look into something like that once I figure out why the sparse matrix multiplication is slow.

**Comment by joehuchette** [comment]
This looks great, and ready to go from my end. Thanks for your hard work, @ExpandingMan!

**Comment by ExpandingMan** [comment]
Awesome!  Thanks all, glad to have contributed.
