### PR TITLE
Fix product of sparse matrices for Julia v1.3

### LINKED ISSUE #2042: Style: interpolated variables in strings need parentheses
I propose that all interpolated variables in strings need parentheses.

> Good:
> ```Julia
> x = 1
> "Interpolated x=$(x) with parentheses.
> ```
>
> Bad:
> ```Julia
> x = 1
> "Interpolated x=$x without parentheses.
> ```

This stems from a potential breaking change between Julia 1.2 and Julia 1.3. See https://github.com/JuliaLang/julia/issues/33044.

### PR DESCRIPTION
**Pull request by blegat**
Closes https://github.com/JuliaOpt/JuMP.jl/issues/1276
Closes https://github.com/JuliaOpt/JuMP.jl/issues/2054
Closes #2042 
Closes #2043

### CODE REVIEW

File: src/operators.jl [hunk 1]
```diff
@@ -449,23 +452,54 @@ function _mul!(ret::AbstractVecOrMat{<:GenericAffOrQuadExpr},
 end
 
 function _mul!(ret::AbstractMatrix{<:GenericAffOrQuadExpr},
-               A::AbstractMatrix, B::SparseMatrixCSC)
-    _fill_with_zeros!(ret)
+               A::AbstractMatrix, B::SparseMatrixCSC,
+               α_expr=one(eltype(ret)),
+               β=zero(eltype(ret)))
```
Comment (odow) [inline src/operators.jl]: When are these called with anything other than the defaults?

**Comment by odow** [comment]
You can probably add
```
Closes #2042 
Closes #2043
```
It doesn't look like we'll move forward, given the resolution up-stream. It's something `JuliaFormatter` can handle as well.

File: src/operators.jl (hunk 1 above)
Comment (blegat) [reply src/operators.jl]: I can't find anywhere it's called with values different from alpha=one and beta=zero in `SparseArrays/src/linalg.jl`. I don't know where it's documented either
