### PR TITLE
Make SDP example work, move it, close #1547

### LINKED ISSUE #1547: `maxcut_sdp.jl` needs to be updated // currently with an assertion fail
`JuMP.jl/examples/old/maxcut_sdp.jl` needs attention. An assertion fails, likely due to some issues regarding Cholesky decomposition. 

#1538 

https://github.com/JuliaOpt/JuMP.jl/blob/27e710261aa935112b4c0623cdbd24ceee93ce41/examples/old/maxcut_sdp.jl

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

File: examples/maxcut_sdp.jl [hunk 1]
```diff
@@ -0,0 +1,143 @@
+#############################################################################
+# JuMP
```
Comment (mlubin) [inline examples/maxcut_sdp.jl]: Missing license header

File: examples/maxcut_sdp.jl [hunk 2]
```diff
@@ -0,0 +1,143 @@
...
+
+    # Solve the SDP relaxation
+    model = Model(with_optimizer(SCS.Optimizer))
+    @variable(model, X[1:num_vertex, 1:num_vertex], PSD)
+    @objective(model, Max, 1/4 * dot(laplacian, X))
+    @constraint(model, diag(X) .== 1)
+    JuMP.optimize!(model)
+ 
+    # Compute the Cholesky factorization of X, i.e., X = V^T V.
+    opt_X = Hermitian(JuMP.result_value.(X), :U)  # Tell Julia its PSD.
```
Comment (mlubin) [inline examples/maxcut_sdp.jl]: `result_value` was renamed to `value`
