### PR TITLE
Fix isassigned for DenseAxisArray

### LINKED ISSUE #1923: Incosistent `isassigned` behavior for DenseAxisArrays
The behavior of the `isassigned` function is not consistent. See example

```Julia
using Random
names1 = Vector{String}(undef, 20)
for n in 1:20
    names1[n] = randstring()
end

cont1 = JuMP.Containers.DenseAxisArray{GenericAffExpr}(undef, 1:10, 1:50);
cont2 = JuMP.Containers.DenseAxisArray{GenericAffExpr}(undef, names1, 1:50);

isassigned(cont1, 1, 1)
>true
isassigned(cont2, names1[1], 1)
>true
```

In these two cases, the result should be `false` since the Arrays are not defined.

### PR DESCRIPTION
**Pull request by odow**
Closes #1923

### CODE REVIEW

File: src/Containers/DenseAxisArray.jl [hunk 1]
```diff
@@ -111,9 +111,25 @@ Base.CartesianIndices(a::DenseAxisArray) = CartesianIndices(a.data)
...
+        return isassigned(A.data, keys...)
+    end
+    return false
+end
+function Base.isassigned(A::DenseAxisArray{T,N}, idx...) where {T,N}
+    return _is_assigned(A, idx...)
+end
 # For ambiguity
-Base.isassigned(A::DenseAxisArray{T,N}, idx::Int...) where {T,N} = length(idx) == N && all(t -> haskey(A.lookup[t[1]], t[2]), enumerate(idx))
+function Base.isassigned(A::DenseAxisArray{T,N}, idx::Int...) where {T,N}
```
Comment (mlubin) [inline src/Containers/DenseAxisArray.jl]: Style nit: `{T, N}` (missing space after comma)
